package org.csc.wlt.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class CscWltContractRecordExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	protected int offset;

	protected int limit;

	protected String sumCol;

	protected String groupSelClause;

	protected boolean forUpdate;

	protected String groupByClause;

	String selectCols;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public CscWltContractRecordExample() {
		oredCriteria = new ArrayList<Criteria>();
		offset = 0;
		limit = Integer.MAX_VALUE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
		this.offset = 0;
		this.limit = Integer.MAX_VALUE;
		this.sumCol = null;
		this.groupSelClause = null;
		this.groupByClause = null;
		this.forUpdate = false;
	}

	public void setOffset(int offset) {
		this.offset = offset;
	}

	public int getOffset() {
		return offset;
	}

	public void setLimit(int limit) {
		this.limit = limit;
	}

	public int getLimit() {
		return limit;
	}

	public void setSumCol(String sumCol) {
		this.sumCol = sumCol;
	}

	public String getSumCol() {
		return sumCol;
	}

	public void setGroupSelClause(String groupSelClause) {
		this.groupSelClause = groupSelClause;
	}

	public String getGroupSelClause() {
		return groupSelClause;
	}

	public void setForUpdate(boolean forUpdate) {
		this.forUpdate = forUpdate;
	}

	public boolean isForUpdate() {
		return forUpdate;
	}

	public void setGroupByClause(String groupByClause) {
		this.groupByClause = groupByClause;
	}

	public String getGroupByClause() {
		return groupByClause;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Data
	public abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		public GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		public void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		public void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		public void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andRecoedIdIsNull() {
			addCriterion("recoed_id is null");
			return (Criteria) this;
		}

		public Criteria andRecoedIdIsNotNull() {
			addCriterion("recoed_id is not null");
			return (Criteria) this;
		}

		public Criteria andRecoedIdEqualTo(String value) {
			addCriterion("recoed_id =", value, "recoedId");
			return (Criteria) this;
		}

		public Criteria andRecoedIdNotEqualTo(String value) {
			addCriterion("recoed_id <>", value, "recoedId");
			return (Criteria) this;
		}

		public Criteria andRecoedIdGreaterThan(String value) {
			addCriterion("recoed_id >", value, "recoedId");
			return (Criteria) this;
		}

		public Criteria andRecoedIdGreaterThanOrEqualTo(String value) {
			addCriterion("recoed_id >=", value, "recoedId");
			return (Criteria) this;
		}

		public Criteria andRecoedIdLessThan(String value) {
			addCriterion("recoed_id <", value, "recoedId");
			return (Criteria) this;
		}

		public Criteria andRecoedIdLessThanOrEqualTo(String value) {
			addCriterion("recoed_id <=", value, "recoedId");
			return (Criteria) this;
		}

		public Criteria andRecoedIdLike(String value) {
			addCriterion("recoed_id like", value, "recoedId");
			return (Criteria) this;
		}

		public Criteria andRecoedIdNotLike(String value) {
			addCriterion("recoed_id not like", value, "recoedId");
			return (Criteria) this;
		}

		public Criteria andRecoedIdIn(List<String> values) {
			addCriterion("recoed_id in", values, "recoedId");
			return (Criteria) this;
		}

		public Criteria andRecoedIdNotIn(List<String> values) {
			addCriterion("recoed_id not in", values, "recoedId");
			return (Criteria) this;
		}

		public Criteria andRecoedIdBetween(String value1, String value2) {
			addCriterion("recoed_id between", value1, value2, "recoedId");
			return (Criteria) this;
		}

		public Criteria andRecoedIdNotBetween(String value1, String value2) {
			addCriterion("recoed_id not between", value1, value2, "recoedId");
			return (Criteria) this;
		}

		public Criteria andContractIdIsNull() {
			addCriterion("contract_id is null");
			return (Criteria) this;
		}

		public Criteria andContractIdIsNotNull() {
			addCriterion("contract_id is not null");
			return (Criteria) this;
		}

		public Criteria andContractIdEqualTo(String value) {
			addCriterion("contract_id =", value, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdNotEqualTo(String value) {
			addCriterion("contract_id <>", value, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdGreaterThan(String value) {
			addCriterion("contract_id >", value, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdGreaterThanOrEqualTo(String value) {
			addCriterion("contract_id >=", value, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdLessThan(String value) {
			addCriterion("contract_id <", value, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdLessThanOrEqualTo(String value) {
			addCriterion("contract_id <=", value, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdLike(String value) {
			addCriterion("contract_id like", value, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdNotLike(String value) {
			addCriterion("contract_id not like", value, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdIn(List<String> values) {
			addCriterion("contract_id in", values, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdNotIn(List<String> values) {
			addCriterion("contract_id not in", values, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdBetween(String value1, String value2) {
			addCriterion("contract_id between", value1, value2, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdNotBetween(String value1, String value2) {
			addCriterion("contract_id not between", value1, value2, "contractId");
			return (Criteria) this;
		}

		public Criteria andRecordTypeIsNull() {
			addCriterion("record_type is null");
			return (Criteria) this;
		}

		public Criteria andRecordTypeIsNotNull() {
			addCriterion("record_type is not null");
			return (Criteria) this;
		}

		public Criteria andRecordTypeEqualTo(String value) {
			addCriterion("record_type =", value, "recordType");
			return (Criteria) this;
		}

		public Criteria andRecordTypeNotEqualTo(String value) {
			addCriterion("record_type <>", value, "recordType");
			return (Criteria) this;
		}

		public Criteria andRecordTypeGreaterThan(String value) {
			addCriterion("record_type >", value, "recordType");
			return (Criteria) this;
		}

		public Criteria andRecordTypeGreaterThanOrEqualTo(String value) {
			addCriterion("record_type >=", value, "recordType");
			return (Criteria) this;
		}

		public Criteria andRecordTypeLessThan(String value) {
			addCriterion("record_type <", value, "recordType");
			return (Criteria) this;
		}

		public Criteria andRecordTypeLessThanOrEqualTo(String value) {
			addCriterion("record_type <=", value, "recordType");
			return (Criteria) this;
		}

		public Criteria andRecordTypeLike(String value) {
			addCriterion("record_type like", value, "recordType");
			return (Criteria) this;
		}

		public Criteria andRecordTypeNotLike(String value) {
			addCriterion("record_type not like", value, "recordType");
			return (Criteria) this;
		}

		public Criteria andRecordTypeIn(List<String> values) {
			addCriterion("record_type in", values, "recordType");
			return (Criteria) this;
		}

		public Criteria andRecordTypeNotIn(List<String> values) {
			addCriterion("record_type not in", values, "recordType");
			return (Criteria) this;
		}

		public Criteria andRecordTypeBetween(String value1, String value2) {
			addCriterion("record_type between", value1, value2, "recordType");
			return (Criteria) this;
		}

		public Criteria andRecordTypeNotBetween(String value1, String value2) {
			addCriterion("record_type not between", value1, value2, "recordType");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andTxHashIsNull() {
			addCriterion("tx_hash is null");
			return (Criteria) this;
		}

		public Criteria andTxHashIsNotNull() {
			addCriterion("tx_hash is not null");
			return (Criteria) this;
		}

		public Criteria andTxHashEqualTo(String value) {
			addCriterion("tx_hash =", value, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashNotEqualTo(String value) {
			addCriterion("tx_hash <>", value, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashGreaterThan(String value) {
			addCriterion("tx_hash >", value, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashGreaterThanOrEqualTo(String value) {
			addCriterion("tx_hash >=", value, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashLessThan(String value) {
			addCriterion("tx_hash <", value, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashLessThanOrEqualTo(String value) {
			addCriterion("tx_hash <=", value, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashLike(String value) {
			addCriterion("tx_hash like", value, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashNotLike(String value) {
			addCriterion("tx_hash not like", value, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashIn(List<String> values) {
			addCriterion("tx_hash in", values, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashNotIn(List<String> values) {
			addCriterion("tx_hash not in", values, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashBetween(String value1, String value2) {
			addCriterion("tx_hash between", value1, value2, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashNotBetween(String value1, String value2) {
			addCriterion("tx_hash not between", value1, value2, "txHash");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeIsNull() {
			addCriterion("created_time is null");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeIsNotNull() {
			addCriterion("created_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeEqualTo(Date value) {
			addCriterion("created_time =", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeNotEqualTo(Date value) {
			addCriterion("created_time <>", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeGreaterThan(Date value) {
			addCriterion("created_time >", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("created_time >=", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeLessThan(Date value) {
			addCriterion("created_time <", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
			addCriterion("created_time <=", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeIn(List<Date> values) {
			addCriterion("created_time in", values, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeNotIn(List<Date> values) {
			addCriterion("created_time not in", values, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeBetween(Date value1, Date value2) {
			addCriterion("created_time between", value1, value2, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
			addCriterion("created_time not between", value1, value2, "createdTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeIsNull() {
			addCriterion("updated_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeIsNotNull() {
			addCriterion("updated_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeEqualTo(Date value) {
			addCriterion("updated_time =", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeNotEqualTo(Date value) {
			addCriterion("updated_time <>", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeGreaterThan(Date value) {
			addCriterion("updated_time >", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("updated_time >=", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeLessThan(Date value) {
			addCriterion("updated_time <", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeLessThanOrEqualTo(Date value) {
			addCriterion("updated_time <=", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeIn(List<Date> values) {
			addCriterion("updated_time in", values, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeNotIn(List<Date> values) {
			addCriterion("updated_time not in", values, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeBetween(Date value1, Date value2) {
			addCriterion("updated_time between", value1, value2, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeNotBetween(Date value1, Date value2) {
			addCriterion("updated_time not between", value1, value2, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andReserved1IsNull() {
			addCriterion("reserved1 is null");
			return (Criteria) this;
		}

		public Criteria andReserved1IsNotNull() {
			addCriterion("reserved1 is not null");
			return (Criteria) this;
		}

		public Criteria andReserved1EqualTo(String value) {
			addCriterion("reserved1 =", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1NotEqualTo(String value) {
			addCriterion("reserved1 <>", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1GreaterThan(String value) {
			addCriterion("reserved1 >", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1GreaterThanOrEqualTo(String value) {
			addCriterion("reserved1 >=", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1LessThan(String value) {
			addCriterion("reserved1 <", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1LessThanOrEqualTo(String value) {
			addCriterion("reserved1 <=", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1Like(String value) {
			addCriterion("reserved1 like", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1NotLike(String value) {
			addCriterion("reserved1 not like", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1In(List<String> values) {
			addCriterion("reserved1 in", values, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1NotIn(List<String> values) {
			addCriterion("reserved1 not in", values, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1Between(String value1, String value2) {
			addCriterion("reserved1 between", value1, value2, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1NotBetween(String value1, String value2) {
			addCriterion("reserved1 not between", value1, value2, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved2IsNull() {
			addCriterion("reserved2 is null");
			return (Criteria) this;
		}

		public Criteria andReserved2IsNotNull() {
			addCriterion("reserved2 is not null");
			return (Criteria) this;
		}

		public Criteria andReserved2EqualTo(String value) {
			addCriterion("reserved2 =", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2NotEqualTo(String value) {
			addCriterion("reserved2 <>", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2GreaterThan(String value) {
			addCriterion("reserved2 >", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2GreaterThanOrEqualTo(String value) {
			addCriterion("reserved2 >=", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2LessThan(String value) {
			addCriterion("reserved2 <", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2LessThanOrEqualTo(String value) {
			addCriterion("reserved2 <=", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2Like(String value) {
			addCriterion("reserved2 like", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2NotLike(String value) {
			addCriterion("reserved2 not like", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2In(List<String> values) {
			addCriterion("reserved2 in", values, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2NotIn(List<String> values) {
			addCriterion("reserved2 not in", values, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2Between(String value1, String value2) {
			addCriterion("reserved2 between", value1, value2, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2NotBetween(String value1, String value2) {
			addCriterion("reserved2 not between", value1, value2, "reserved2");
			return (Criteria) this;
		}

		public Criteria andRecoedIdLikeInsensitive(String value) {
			addCriterion("upper(recoed_id) like", value.toUpperCase(), "recoedId");
			return (Criteria) this;
		}

		public Criteria andContractIdLikeInsensitive(String value) {
			addCriterion("upper(contract_id) like", value.toUpperCase(), "contractId");
			return (Criteria) this;
		}

		public Criteria andRecordTypeLikeInsensitive(String value) {
			addCriterion("upper(record_type) like", value.toUpperCase(), "recordType");
			return (Criteria) this;
		}

		public Criteria andAddressLikeInsensitive(String value) {
			addCriterion("upper(address) like", value.toUpperCase(), "address");
			return (Criteria) this;
		}

		public Criteria andTxHashLikeInsensitive(String value) {
			addCriterion("upper(tx_hash) like", value.toUpperCase(), "txHash");
			return (Criteria) this;
		}

		public Criteria andReserved1LikeInsensitive(String value) {
			addCriterion("upper(reserved1) like", value.toUpperCase(), "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved2LikeInsensitive(String value) {
			addCriterion("upper(reserved2) like", value.toUpperCase(), "reserved2");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table csc_wlt_contract_record
	 *
	 * @mbggenerated do_not_delete_during_merge Fri Jun 08 18:04:10 CST 2018
	 */
	public static class Criteria extends GeneratedCriteria {

		public Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Data
	@NoArgsConstructor
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		public Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		public Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		public Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		public Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}