package org.csc.wlt.entity;

import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;

@Tab(name = "csc_wlt_contract")
@AllArgsConstructor
@NoArgsConstructor
public class CscWltContract extends CscWltContractKey {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column csc_wlt_contract.contract_address
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private String contractAddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column csc_wlt_contract.contract_tx_hash
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private String contractTxHash;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column csc_wlt_contract.contract_type
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private String contractType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column csc_wlt_contract.contract_name
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private String contractName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column csc_wlt_contract.contract_status
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private String contractStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column csc_wlt_contract.created_time
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private Date createdTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column csc_wlt_contract.updated_time
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private Date updatedTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column csc_wlt_contract.reserved1
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private String reserved1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column csc_wlt_contract.reserved2
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private String reserved2;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column csc_wlt_contract.contract_address
	 *
	 * @return the value of csc_wlt_contract.contract_address
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getContractAddress() {
		return contractAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column csc_wlt_contract.contract_address
	 *
	 * @param contractAddress the value for csc_wlt_contract.contract_address
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setContractAddress(String contractAddress) {
		this.contractAddress = contractAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column csc_wlt_contract.contract_tx_hash
	 *
	 * @return the value of csc_wlt_contract.contract_tx_hash
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getContractTxHash() {
		return contractTxHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column csc_wlt_contract.contract_tx_hash
	 *
	 * @param contractTxHash the value for csc_wlt_contract.contract_tx_hash
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setContractTxHash(String contractTxHash) {
		this.contractTxHash = contractTxHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column csc_wlt_contract.contract_type
	 *
	 * @return the value of csc_wlt_contract.contract_type
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getContractType() {
		return contractType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column csc_wlt_contract.contract_type
	 *
	 * @param contractType the value for csc_wlt_contract.contract_type
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setContractType(String contractType) {
		this.contractType = contractType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column csc_wlt_contract.contract_name
	 *
	 * @return the value of csc_wlt_contract.contract_name
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getContractName() {
		return contractName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column csc_wlt_contract.contract_name
	 *
	 * @param contractName the value for csc_wlt_contract.contract_name
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setContractName(String contractName) {
		this.contractName = contractName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column csc_wlt_contract.contract_status
	 *
	 * @return the value of csc_wlt_contract.contract_status
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getContractStatus() {
		return contractStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column csc_wlt_contract.contract_status
	 *
	 * @param contractStatus the value for csc_wlt_contract.contract_status
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setContractStatus(String contractStatus) {
		this.contractStatus = contractStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column csc_wlt_contract.created_time
	 *
	 * @return the value of csc_wlt_contract.created_time
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column csc_wlt_contract.created_time
	 *
	 * @param createdTime the value for csc_wlt_contract.created_time
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column csc_wlt_contract.updated_time
	 *
	 * @return the value of csc_wlt_contract.updated_time
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public Date getUpdatedTime() {
		return updatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column csc_wlt_contract.updated_time
	 *
	 * @param updatedTime the value for csc_wlt_contract.updated_time
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column csc_wlt_contract.reserved1
	 *
	 * @return the value of csc_wlt_contract.reserved1
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getReserved1() {
		return reserved1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column csc_wlt_contract.reserved1
	 *
	 * @param reserved1 the value for csc_wlt_contract.reserved1
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setReserved1(String reserved1) {
		this.reserved1 = reserved1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column csc_wlt_contract.reserved2
	 *
	 * @return the value of csc_wlt_contract.reserved2
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getReserved2() {
		return reserved2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column csc_wlt_contract.reserved2
	 *
	 * @param reserved2 the value for csc_wlt_contract.reserved2
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setReserved2(String reserved2) {
		this.reserved2 = reserved2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		CscWltContract other = (CscWltContract) that;
		return (this.getContractId() == null ? other.getContractId() == null
				: this.getContractId().equals(other.getContractId()))
				&& (this.getContractAddress() == null ? other.getContractAddress() == null
						: this.getContractAddress().equals(other.getContractAddress()))
				&& (this.getContractTxHash() == null ? other.getContractTxHash() == null
						: this.getContractTxHash().equals(other.getContractTxHash()))
				&& (this.getContractType() == null ? other.getContractType() == null
						: this.getContractType().equals(other.getContractType()))
				&& (this.getContractName() == null ? other.getContractName() == null
						: this.getContractName().equals(other.getContractName()))
				&& (this.getContractStatus() == null ? other.getContractStatus() == null
						: this.getContractStatus().equals(other.getContractStatus()))
				&& (this.getCreatedTime() == null ? other.getCreatedTime() == null
						: this.getCreatedTime().equals(other.getCreatedTime()))
				&& (this.getUpdatedTime() == null ? other.getUpdatedTime() == null
						: this.getUpdatedTime().equals(other.getUpdatedTime()))
				&& (this.getReserved1() == null ? other.getReserved1() == null
						: this.getReserved1().equals(other.getReserved1()))
				&& (this.getReserved2() == null ? other.getReserved2() == null
						: this.getReserved2().equals(other.getReserved2()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getContractId() == null) ? 0 : getContractId().hashCode());
		result = prime * result + ((getContractAddress() == null) ? 0 : getContractAddress().hashCode());
		result = prime * result + ((getContractTxHash() == null) ? 0 : getContractTxHash().hashCode());
		result = prime * result + ((getContractType() == null) ? 0 : getContractType().hashCode());
		result = prime * result + ((getContractName() == null) ? 0 : getContractName().hashCode());
		result = prime * result + ((getContractStatus() == null) ? 0 : getContractStatus().hashCode());
		result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
		result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
		result = prime * result + ((getReserved1() == null) ? 0 : getReserved1().hashCode());
		result = prime * result + ((getReserved2() == null) ? 0 : getReserved2().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", contractAddress=").append(contractAddress);
		sb.append(", contractTxHash=").append(contractTxHash);
		sb.append(", contractType=").append(contractType);
		sb.append(", contractName=").append(contractName);
		sb.append(", contractStatus=").append(contractStatus);
		sb.append(", createdTime=").append(createdTime);
		sb.append(", updatedTime=").append(updatedTime);
		sb.append(", reserved1=").append(reserved1);
		sb.append(", reserved2=").append(reserved2);
		sb.append("]");
		return sb.toString();
	}
}