package org.csc.wlt.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class CscWltTxExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	protected int offset;

	protected int limit;

	protected String sumCol;

	protected String groupSelClause;

	protected boolean forUpdate;

	protected String groupByClause;

	String selectCols;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public CscWltTxExample() {
		oredCriteria = new ArrayList<Criteria>();
		offset = 0;
		limit = Integer.MAX_VALUE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
		this.offset = 0;
		this.limit = Integer.MAX_VALUE;
		this.sumCol = null;
		this.groupSelClause = null;
		this.groupByClause = null;
		this.forUpdate = false;
	}

	public void setOffset(int offset) {
		this.offset = offset;
	}

	public int getOffset() {
		return offset;
	}

	public void setLimit(int limit) {
		this.limit = limit;
	}

	public int getLimit() {
		return limit;
	}

	public void setSumCol(String sumCol) {
		this.sumCol = sumCol;
	}

	public String getSumCol() {
		return sumCol;
	}

	public void setGroupSelClause(String groupSelClause) {
		this.groupSelClause = groupSelClause;
	}

	public String getGroupSelClause() {
		return groupSelClause;
	}

	public void setForUpdate(boolean forUpdate) {
		this.forUpdate = forUpdate;
	}

	public boolean isForUpdate() {
		return forUpdate;
	}

	public void setGroupByClause(String groupByClause) {
		this.groupByClause = groupByClause;
	}

	public String getGroupByClause() {
		return groupByClause;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Data
	public abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		public GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		public void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		public void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		public void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andTxIdIsNull() {
			addCriterion("tx_id is null");
			return (Criteria) this;
		}

		public Criteria andTxIdIsNotNull() {
			addCriterion("tx_id is not null");
			return (Criteria) this;
		}

		public Criteria andTxIdEqualTo(String value) {
			addCriterion("tx_id =", value, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdNotEqualTo(String value) {
			addCriterion("tx_id <>", value, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdGreaterThan(String value) {
			addCriterion("tx_id >", value, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdGreaterThanOrEqualTo(String value) {
			addCriterion("tx_id >=", value, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdLessThan(String value) {
			addCriterion("tx_id <", value, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdLessThanOrEqualTo(String value) {
			addCriterion("tx_id <=", value, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdLike(String value) {
			addCriterion("tx_id like", value, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdNotLike(String value) {
			addCriterion("tx_id not like", value, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdIn(List<String> values) {
			addCriterion("tx_id in", values, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdNotIn(List<String> values) {
			addCriterion("tx_id not in", values, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdBetween(String value1, String value2) {
			addCriterion("tx_id between", value1, value2, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdNotBetween(String value1, String value2) {
			addCriterion("tx_id not between", value1, value2, "txId");
			return (Criteria) this;
		}

		public Criteria andTxHashIsNull() {
			addCriterion("tx_hash is null");
			return (Criteria) this;
		}

		public Criteria andTxHashIsNotNull() {
			addCriterion("tx_hash is not null");
			return (Criteria) this;
		}

		public Criteria andTxHashEqualTo(String value) {
			addCriterion("tx_hash =", value, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashNotEqualTo(String value) {
			addCriterion("tx_hash <>", value, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashGreaterThan(String value) {
			addCriterion("tx_hash >", value, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashGreaterThanOrEqualTo(String value) {
			addCriterion("tx_hash >=", value, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashLessThan(String value) {
			addCriterion("tx_hash <", value, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashLessThanOrEqualTo(String value) {
			addCriterion("tx_hash <=", value, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashLike(String value) {
			addCriterion("tx_hash like", value, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashNotLike(String value) {
			addCriterion("tx_hash not like", value, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashIn(List<String> values) {
			addCriterion("tx_hash in", values, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashNotIn(List<String> values) {
			addCriterion("tx_hash not in", values, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashBetween(String value1, String value2) {
			addCriterion("tx_hash between", value1, value2, "txHash");
			return (Criteria) this;
		}

		public Criteria andTxHashNotBetween(String value1, String value2) {
			addCriterion("tx_hash not between", value1, value2, "txHash");
			return (Criteria) this;
		}

		public Criteria andInputAddressIsNull() {
			addCriterion("input_address is null");
			return (Criteria) this;
		}

		public Criteria andInputAddressIsNotNull() {
			addCriterion("input_address is not null");
			return (Criteria) this;
		}

		public Criteria andInputAddressEqualTo(String value) {
			addCriterion("input_address =", value, "inputAddress");
			return (Criteria) this;
		}

		public Criteria andInputAddressNotEqualTo(String value) {
			addCriterion("input_address <>", value, "inputAddress");
			return (Criteria) this;
		}

		public Criteria andInputAddressGreaterThan(String value) {
			addCriterion("input_address >", value, "inputAddress");
			return (Criteria) this;
		}

		public Criteria andInputAddressGreaterThanOrEqualTo(String value) {
			addCriterion("input_address >=", value, "inputAddress");
			return (Criteria) this;
		}

		public Criteria andInputAddressLessThan(String value) {
			addCriterion("input_address <", value, "inputAddress");
			return (Criteria) this;
		}

		public Criteria andInputAddressLessThanOrEqualTo(String value) {
			addCriterion("input_address <=", value, "inputAddress");
			return (Criteria) this;
		}

		public Criteria andInputAddressLike(String value) {
			addCriterion("input_address like", value, "inputAddress");
			return (Criteria) this;
		}

		public Criteria andInputAddressNotLike(String value) {
			addCriterion("input_address not like", value, "inputAddress");
			return (Criteria) this;
		}

		public Criteria andInputAddressIn(List<String> values) {
			addCriterion("input_address in", values, "inputAddress");
			return (Criteria) this;
		}

		public Criteria andInputAddressNotIn(List<String> values) {
			addCriterion("input_address not in", values, "inputAddress");
			return (Criteria) this;
		}

		public Criteria andInputAddressBetween(String value1, String value2) {
			addCriterion("input_address between", value1, value2, "inputAddress");
			return (Criteria) this;
		}

		public Criteria andInputAddressNotBetween(String value1, String value2) {
			addCriterion("input_address not between", value1, value2, "inputAddress");
			return (Criteria) this;
		}

		public Criteria andOutputAddressIsNull() {
			addCriterion("output_address is null");
			return (Criteria) this;
		}

		public Criteria andOutputAddressIsNotNull() {
			addCriterion("output_address is not null");
			return (Criteria) this;
		}

		public Criteria andOutputAddressEqualTo(String value) {
			addCriterion("output_address =", value, "outputAddress");
			return (Criteria) this;
		}

		public Criteria andOutputAddressNotEqualTo(String value) {
			addCriterion("output_address <>", value, "outputAddress");
			return (Criteria) this;
		}

		public Criteria andOutputAddressGreaterThan(String value) {
			addCriterion("output_address >", value, "outputAddress");
			return (Criteria) this;
		}

		public Criteria andOutputAddressGreaterThanOrEqualTo(String value) {
			addCriterion("output_address >=", value, "outputAddress");
			return (Criteria) this;
		}

		public Criteria andOutputAddressLessThan(String value) {
			addCriterion("output_address <", value, "outputAddress");
			return (Criteria) this;
		}

		public Criteria andOutputAddressLessThanOrEqualTo(String value) {
			addCriterion("output_address <=", value, "outputAddress");
			return (Criteria) this;
		}

		public Criteria andOutputAddressLike(String value) {
			addCriterion("output_address like", value, "outputAddress");
			return (Criteria) this;
		}

		public Criteria andOutputAddressNotLike(String value) {
			addCriterion("output_address not like", value, "outputAddress");
			return (Criteria) this;
		}

		public Criteria andOutputAddressIn(List<String> values) {
			addCriterion("output_address in", values, "outputAddress");
			return (Criteria) this;
		}

		public Criteria andOutputAddressNotIn(List<String> values) {
			addCriterion("output_address not in", values, "outputAddress");
			return (Criteria) this;
		}

		public Criteria andOutputAddressBetween(String value1, String value2) {
			addCriterion("output_address between", value1, value2, "outputAddress");
			return (Criteria) this;
		}

		public Criteria andOutputAddressNotBetween(String value1, String value2) {
			addCriterion("output_address not between", value1, value2, "outputAddress");
			return (Criteria) this;
		}

		public Criteria andAmountIsNull() {
			addCriterion("amount is null");
			return (Criteria) this;
		}

		public Criteria andAmountIsNotNull() {
			addCriterion("amount is not null");
			return (Criteria) this;
		}

		public Criteria andAmountEqualTo(Long value) {
			addCriterion("amount =", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotEqualTo(Long value) {
			addCriterion("amount <>", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThan(Long value) {
			addCriterion("amount >", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThanOrEqualTo(Long value) {
			addCriterion("amount >=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThan(Long value) {
			addCriterion("amount <", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThanOrEqualTo(Long value) {
			addCriterion("amount <=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountIn(List<Long> values) {
			addCriterion("amount in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotIn(List<Long> values) {
			addCriterion("amount not in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountBetween(Long value1, Long value2) {
			addCriterion("amount between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotBetween(Long value1, Long value2) {
			addCriterion("amount not between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andTxStatusIsNull() {
			addCriterion("tx_status is null");
			return (Criteria) this;
		}

		public Criteria andTxStatusIsNotNull() {
			addCriterion("tx_status is not null");
			return (Criteria) this;
		}

		public Criteria andTxStatusEqualTo(String value) {
			addCriterion("tx_status =", value, "txStatus");
			return (Criteria) this;
		}

		public Criteria andTxStatusNotEqualTo(String value) {
			addCriterion("tx_status <>", value, "txStatus");
			return (Criteria) this;
		}

		public Criteria andTxStatusGreaterThan(String value) {
			addCriterion("tx_status >", value, "txStatus");
			return (Criteria) this;
		}

		public Criteria andTxStatusGreaterThanOrEqualTo(String value) {
			addCriterion("tx_status >=", value, "txStatus");
			return (Criteria) this;
		}

		public Criteria andTxStatusLessThan(String value) {
			addCriterion("tx_status <", value, "txStatus");
			return (Criteria) this;
		}

		public Criteria andTxStatusLessThanOrEqualTo(String value) {
			addCriterion("tx_status <=", value, "txStatus");
			return (Criteria) this;
		}

		public Criteria andTxStatusLike(String value) {
			addCriterion("tx_status like", value, "txStatus");
			return (Criteria) this;
		}

		public Criteria andTxStatusNotLike(String value) {
			addCriterion("tx_status not like", value, "txStatus");
			return (Criteria) this;
		}

		public Criteria andTxStatusIn(List<String> values) {
			addCriterion("tx_status in", values, "txStatus");
			return (Criteria) this;
		}

		public Criteria andTxStatusNotIn(List<String> values) {
			addCriterion("tx_status not in", values, "txStatus");
			return (Criteria) this;
		}

		public Criteria andTxStatusBetween(String value1, String value2) {
			addCriterion("tx_status between", value1, value2, "txStatus");
			return (Criteria) this;
		}

		public Criteria andTxStatusNotBetween(String value1, String value2) {
			addCriterion("tx_status not between", value1, value2, "txStatus");
			return (Criteria) this;
		}

		public Criteria andTxTypeIsNull() {
			addCriterion("tx_type is null");
			return (Criteria) this;
		}

		public Criteria andTxTypeIsNotNull() {
			addCriterion("tx_type is not null");
			return (Criteria) this;
		}

		public Criteria andTxTypeEqualTo(String value) {
			addCriterion("tx_type =", value, "txType");
			return (Criteria) this;
		}

		public Criteria andTxTypeNotEqualTo(String value) {
			addCriterion("tx_type <>", value, "txType");
			return (Criteria) this;
		}

		public Criteria andTxTypeGreaterThan(String value) {
			addCriterion("tx_type >", value, "txType");
			return (Criteria) this;
		}

		public Criteria andTxTypeGreaterThanOrEqualTo(String value) {
			addCriterion("tx_type >=", value, "txType");
			return (Criteria) this;
		}

		public Criteria andTxTypeLessThan(String value) {
			addCriterion("tx_type <", value, "txType");
			return (Criteria) this;
		}

		public Criteria andTxTypeLessThanOrEqualTo(String value) {
			addCriterion("tx_type <=", value, "txType");
			return (Criteria) this;
		}

		public Criteria andTxTypeLike(String value) {
			addCriterion("tx_type like", value, "txType");
			return (Criteria) this;
		}

		public Criteria andTxTypeNotLike(String value) {
			addCriterion("tx_type not like", value, "txType");
			return (Criteria) this;
		}

		public Criteria andTxTypeIn(List<String> values) {
			addCriterion("tx_type in", values, "txType");
			return (Criteria) this;
		}

		public Criteria andTxTypeNotIn(List<String> values) {
			addCriterion("tx_type not in", values, "txType");
			return (Criteria) this;
		}

		public Criteria andTxTypeBetween(String value1, String value2) {
			addCriterion("tx_type between", value1, value2, "txType");
			return (Criteria) this;
		}

		public Criteria andTxTypeNotBetween(String value1, String value2) {
			addCriterion("tx_type not between", value1, value2, "txType");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeIsNull() {
			addCriterion("created_time is null");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeIsNotNull() {
			addCriterion("created_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeEqualTo(Date value) {
			addCriterion("created_time =", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeNotEqualTo(Date value) {
			addCriterion("created_time <>", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeGreaterThan(Date value) {
			addCriterion("created_time >", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("created_time >=", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeLessThan(Date value) {
			addCriterion("created_time <", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
			addCriterion("created_time <=", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeIn(List<Date> values) {
			addCriterion("created_time in", values, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeNotIn(List<Date> values) {
			addCriterion("created_time not in", values, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeBetween(Date value1, Date value2) {
			addCriterion("created_time between", value1, value2, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
			addCriterion("created_time not between", value1, value2, "createdTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeIsNull() {
			addCriterion("updated_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeIsNotNull() {
			addCriterion("updated_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeEqualTo(Date value) {
			addCriterion("updated_time =", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeNotEqualTo(Date value) {
			addCriterion("updated_time <>", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeGreaterThan(Date value) {
			addCriterion("updated_time >", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("updated_time >=", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeLessThan(Date value) {
			addCriterion("updated_time <", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeLessThanOrEqualTo(Date value) {
			addCriterion("updated_time <=", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeIn(List<Date> values) {
			addCriterion("updated_time in", values, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeNotIn(List<Date> values) {
			addCriterion("updated_time not in", values, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeBetween(Date value1, Date value2) {
			addCriterion("updated_time between", value1, value2, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeNotBetween(Date value1, Date value2) {
			addCriterion("updated_time not between", value1, value2, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andReserved1IsNull() {
			addCriterion("reserved1 is null");
			return (Criteria) this;
		}

		public Criteria andReserved1IsNotNull() {
			addCriterion("reserved1 is not null");
			return (Criteria) this;
		}

		public Criteria andReserved1EqualTo(String value) {
			addCriterion("reserved1 =", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1NotEqualTo(String value) {
			addCriterion("reserved1 <>", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1GreaterThan(String value) {
			addCriterion("reserved1 >", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1GreaterThanOrEqualTo(String value) {
			addCriterion("reserved1 >=", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1LessThan(String value) {
			addCriterion("reserved1 <", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1LessThanOrEqualTo(String value) {
			addCriterion("reserved1 <=", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1Like(String value) {
			addCriterion("reserved1 like", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1NotLike(String value) {
			addCriterion("reserved1 not like", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1In(List<String> values) {
			addCriterion("reserved1 in", values, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1NotIn(List<String> values) {
			addCriterion("reserved1 not in", values, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1Between(String value1, String value2) {
			addCriterion("reserved1 between", value1, value2, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1NotBetween(String value1, String value2) {
			addCriterion("reserved1 not between", value1, value2, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved2IsNull() {
			addCriterion("reserved2 is null");
			return (Criteria) this;
		}

		public Criteria andReserved2IsNotNull() {
			addCriterion("reserved2 is not null");
			return (Criteria) this;
		}

		public Criteria andReserved2EqualTo(String value) {
			addCriterion("reserved2 =", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2NotEqualTo(String value) {
			addCriterion("reserved2 <>", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2GreaterThan(String value) {
			addCriterion("reserved2 >", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2GreaterThanOrEqualTo(String value) {
			addCriterion("reserved2 >=", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2LessThan(String value) {
			addCriterion("reserved2 <", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2LessThanOrEqualTo(String value) {
			addCriterion("reserved2 <=", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2Like(String value) {
			addCriterion("reserved2 like", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2NotLike(String value) {
			addCriterion("reserved2 not like", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2In(List<String> values) {
			addCriterion("reserved2 in", values, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2NotIn(List<String> values) {
			addCriterion("reserved2 not in", values, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2Between(String value1, String value2) {
			addCriterion("reserved2 between", value1, value2, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2NotBetween(String value1, String value2) {
			addCriterion("reserved2 not between", value1, value2, "reserved2");
			return (Criteria) this;
		}

		public Criteria andTxIdLikeInsensitive(String value) {
			addCriterion("upper(tx_id) like", value.toUpperCase(), "txId");
			return (Criteria) this;
		}

		public Criteria andTxHashLikeInsensitive(String value) {
			addCriterion("upper(tx_hash) like", value.toUpperCase(), "txHash");
			return (Criteria) this;
		}

		public Criteria andInputAddressLikeInsensitive(String value) {
			addCriterion("upper(input_address) like", value.toUpperCase(), "inputAddress");
			return (Criteria) this;
		}

		public Criteria andOutputAddressLikeInsensitive(String value) {
			addCriterion("upper(output_address) like", value.toUpperCase(), "outputAddress");
			return (Criteria) this;
		}

		public Criteria andTxStatusLikeInsensitive(String value) {
			addCriterion("upper(tx_status) like", value.toUpperCase(), "txStatus");
			return (Criteria) this;
		}

		public Criteria andTxTypeLikeInsensitive(String value) {
			addCriterion("upper(tx_type) like", value.toUpperCase(), "txType");
			return (Criteria) this;
		}

		public Criteria andReserved1LikeInsensitive(String value) {
			addCriterion("upper(reserved1) like", value.toUpperCase(), "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved2LikeInsensitive(String value) {
			addCriterion("upper(reserved2) like", value.toUpperCase(), "reserved2");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table cwv_wlt_tx
	 *
	 * @mbggenerated do_not_delete_during_merge Fri Jun 08 18:04:10 CST 2018
	 */
	public static class Criteria extends GeneratedCriteria {

		public Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Data
	@NoArgsConstructor
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		public Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		public Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		public Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		public Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}