package org.csc.wlt.entity;

import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;

@Tab(name = "csc_wlt_contract_record")
@AllArgsConstructor
@NoArgsConstructor
public class CscWltContractRecord extends CscWltContractRecordKey {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column csc_wlt_contract_record.contract_id
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private String contractId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column csc_wlt_contract_record.record_type
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private String recordType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column csc_wlt_contract_record.address
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column csc_wlt_contract_record.tx_hash
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private String txHash;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column csc_wlt_contract_record.created_time
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private Date createdTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column csc_wlt_contract_record.updated_time
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private Date updatedTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column csc_wlt_contract_record.reserved1
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private String reserved1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column csc_wlt_contract_record.reserved2
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private String reserved2;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column csc_wlt_contract_record.contract_id
	 *
	 * @return the value of csc_wlt_contract_record.contract_id
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getContractId() {
		return contractId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column csc_wlt_contract_record.contract_id
	 *
	 * @param contractId the value for csc_wlt_contract_record.contract_id
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setContractId(String contractId) {
		this.contractId = contractId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column csc_wlt_contract_record.record_type
	 *
	 * @return the value of csc_wlt_contract_record.record_type
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getRecordType() {
		return recordType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column csc_wlt_contract_record.record_type
	 *
	 * @param recordType the value for csc_wlt_contract_record.record_type
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setRecordType(String recordType) {
		this.recordType = recordType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column csc_wlt_contract_record.address
	 *
	 * @return the value of csc_wlt_contract_record.address
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column csc_wlt_contract_record.address
	 *
	 * @param address the value for csc_wlt_contract_record.address
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column csc_wlt_contract_record.tx_hash
	 *
	 * @return the value of csc_wlt_contract_record.tx_hash
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getTxHash() {
		return txHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column csc_wlt_contract_record.tx_hash
	 *
	 * @param txHash the value for csc_wlt_contract_record.tx_hash
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setTxHash(String txHash) {
		this.txHash = txHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column csc_wlt_contract_record.created_time
	 *
	 * @return the value of csc_wlt_contract_record.created_time
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column csc_wlt_contract_record.created_time
	 *
	 * @param createdTime the value for csc_wlt_contract_record.created_time
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column csc_wlt_contract_record.updated_time
	 *
	 * @return the value of csc_wlt_contract_record.updated_time
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public Date getUpdatedTime() {
		return updatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column csc_wlt_contract_record.updated_time
	 *
	 * @param updatedTime the value for csc_wlt_contract_record.updated_time
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column csc_wlt_contract_record.reserved1
	 *
	 * @return the value of csc_wlt_contract_record.reserved1
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getReserved1() {
		return reserved1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column csc_wlt_contract_record.reserved1
	 *
	 * @param reserved1 the value for csc_wlt_contract_record.reserved1
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setReserved1(String reserved1) {
		this.reserved1 = reserved1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column csc_wlt_contract_record.reserved2
	 *
	 * @return the value of csc_wlt_contract_record.reserved2
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getReserved2() {
		return reserved2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column csc_wlt_contract_record.reserved2
	 *
	 * @param reserved2 the value for csc_wlt_contract_record.reserved2
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setReserved2(String reserved2) {
		this.reserved2 = reserved2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		CscWltContractRecord other = (CscWltContractRecord) that;
		return (this.getRecoedId() == null ? other.getRecoedId() == null
				: this.getRecoedId().equals(other.getRecoedId()))
				&& (this.getContractId() == null ? other.getContractId() == null
						: this.getContractId().equals(other.getContractId()))
				&& (this.getRecordType() == null ? other.getRecordType() == null
						: this.getRecordType().equals(other.getRecordType()))
				&& (this.getAddress() == null ? other.getAddress() == null
						: this.getAddress().equals(other.getAddress()))
				&& (this.getTxHash() == null ? other.getTxHash() == null : this.getTxHash().equals(other.getTxHash()))
				&& (this.getCreatedTime() == null ? other.getCreatedTime() == null
						: this.getCreatedTime().equals(other.getCreatedTime()))
				&& (this.getUpdatedTime() == null ? other.getUpdatedTime() == null
						: this.getUpdatedTime().equals(other.getUpdatedTime()))
				&& (this.getReserved1() == null ? other.getReserved1() == null
						: this.getReserved1().equals(other.getReserved1()))
				&& (this.getReserved2() == null ? other.getReserved2() == null
						: this.getReserved2().equals(other.getReserved2()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getRecoedId() == null) ? 0 : getRecoedId().hashCode());
		result = prime * result + ((getContractId() == null) ? 0 : getContractId().hashCode());
		result = prime * result + ((getRecordType() == null) ? 0 : getRecordType().hashCode());
		result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
		result = prime * result + ((getTxHash() == null) ? 0 : getTxHash().hashCode());
		result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
		result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
		result = prime * result + ((getReserved1() == null) ? 0 : getReserved1().hashCode());
		result = prime * result + ((getReserved2() == null) ? 0 : getReserved2().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", contractId=").append(contractId);
		sb.append(", recordType=").append(recordType);
		sb.append(", address=").append(address);
		sb.append(", txHash=").append(txHash);
		sb.append(", createdTime=").append(createdTime);
		sb.append(", updatedTime=").append(updatedTime);
		sb.append(", reserved1=").append(reserved1);
		sb.append(", reserved2=").append(reserved2);
		sb.append("]");
		return sb.toString();
	}
}