package org.csc.wlt.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class CscWltContractExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	protected int offset;

	protected int limit;

	protected String sumCol;

	protected String groupSelClause;

	protected boolean forUpdate;

	protected String groupByClause;

	String selectCols;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public CscWltContractExample() {
		oredCriteria = new ArrayList<Criteria>();
		offset = 0;
		limit = Integer.MAX_VALUE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
		this.offset = 0;
		this.limit = Integer.MAX_VALUE;
		this.sumCol = null;
		this.groupSelClause = null;
		this.groupByClause = null;
		this.forUpdate = false;
	}

	public void setOffset(int offset) {
		this.offset = offset;
	}

	public int getOffset() {
		return offset;
	}

	public void setLimit(int limit) {
		this.limit = limit;
	}

	public int getLimit() {
		return limit;
	}

	public void setSumCol(String sumCol) {
		this.sumCol = sumCol;
	}

	public String getSumCol() {
		return sumCol;
	}

	public void setGroupSelClause(String groupSelClause) {
		this.groupSelClause = groupSelClause;
	}

	public String getGroupSelClause() {
		return groupSelClause;
	}

	public void setForUpdate(boolean forUpdate) {
		this.forUpdate = forUpdate;
	}

	public boolean isForUpdate() {
		return forUpdate;
	}

	public void setGroupByClause(String groupByClause) {
		this.groupByClause = groupByClause;
	}

	public String getGroupByClause() {
		return groupByClause;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Data
	public abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		public GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		public void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		public void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		public void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andContractIdIsNull() {
			addCriterion("contract_id is null");
			return (Criteria) this;
		}

		public Criteria andContractIdIsNotNull() {
			addCriterion("contract_id is not null");
			return (Criteria) this;
		}

		public Criteria andContractIdEqualTo(String value) {
			addCriterion("contract_id =", value, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdNotEqualTo(String value) {
			addCriterion("contract_id <>", value, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdGreaterThan(String value) {
			addCriterion("contract_id >", value, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdGreaterThanOrEqualTo(String value) {
			addCriterion("contract_id >=", value, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdLessThan(String value) {
			addCriterion("contract_id <", value, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdLessThanOrEqualTo(String value) {
			addCriterion("contract_id <=", value, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdLike(String value) {
			addCriterion("contract_id like", value, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdNotLike(String value) {
			addCriterion("contract_id not like", value, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdIn(List<String> values) {
			addCriterion("contract_id in", values, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdNotIn(List<String> values) {
			addCriterion("contract_id not in", values, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdBetween(String value1, String value2) {
			addCriterion("contract_id between", value1, value2, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractIdNotBetween(String value1, String value2) {
			addCriterion("contract_id not between", value1, value2, "contractId");
			return (Criteria) this;
		}

		public Criteria andContractAddressIsNull() {
			addCriterion("contract_address is null");
			return (Criteria) this;
		}

		public Criteria andContractAddressIsNotNull() {
			addCriterion("contract_address is not null");
			return (Criteria) this;
		}

		public Criteria andContractAddressEqualTo(String value) {
			addCriterion("contract_address =", value, "contractAddress");
			return (Criteria) this;
		}

		public Criteria andContractAddressNotEqualTo(String value) {
			addCriterion("contract_address <>", value, "contractAddress");
			return (Criteria) this;
		}

		public Criteria andContractAddressGreaterThan(String value) {
			addCriterion("contract_address >", value, "contractAddress");
			return (Criteria) this;
		}

		public Criteria andContractAddressGreaterThanOrEqualTo(String value) {
			addCriterion("contract_address >=", value, "contractAddress");
			return (Criteria) this;
		}

		public Criteria andContractAddressLessThan(String value) {
			addCriterion("contract_address <", value, "contractAddress");
			return (Criteria) this;
		}

		public Criteria andContractAddressLessThanOrEqualTo(String value) {
			addCriterion("contract_address <=", value, "contractAddress");
			return (Criteria) this;
		}

		public Criteria andContractAddressLike(String value) {
			addCriterion("contract_address like", value, "contractAddress");
			return (Criteria) this;
		}

		public Criteria andContractAddressNotLike(String value) {
			addCriterion("contract_address not like", value, "contractAddress");
			return (Criteria) this;
		}

		public Criteria andContractAddressIn(List<String> values) {
			addCriterion("contract_address in", values, "contractAddress");
			return (Criteria) this;
		}

		public Criteria andContractAddressNotIn(List<String> values) {
			addCriterion("contract_address not in", values, "contractAddress");
			return (Criteria) this;
		}

		public Criteria andContractAddressBetween(String value1, String value2) {
			addCriterion("contract_address between", value1, value2, "contractAddress");
			return (Criteria) this;
		}

		public Criteria andContractAddressNotBetween(String value1, String value2) {
			addCriterion("contract_address not between", value1, value2, "contractAddress");
			return (Criteria) this;
		}

		public Criteria andContractTxHashIsNull() {
			addCriterion("contract_tx_hash is null");
			return (Criteria) this;
		}

		public Criteria andContractTxHashIsNotNull() {
			addCriterion("contract_tx_hash is not null");
			return (Criteria) this;
		}

		public Criteria andContractTxHashEqualTo(String value) {
			addCriterion("contract_tx_hash =", value, "contractTxHash");
			return (Criteria) this;
		}

		public Criteria andContractTxHashNotEqualTo(String value) {
			addCriterion("contract_tx_hash <>", value, "contractTxHash");
			return (Criteria) this;
		}

		public Criteria andContractTxHashGreaterThan(String value) {
			addCriterion("contract_tx_hash >", value, "contractTxHash");
			return (Criteria) this;
		}

		public Criteria andContractTxHashGreaterThanOrEqualTo(String value) {
			addCriterion("contract_tx_hash >=", value, "contractTxHash");
			return (Criteria) this;
		}

		public Criteria andContractTxHashLessThan(String value) {
			addCriterion("contract_tx_hash <", value, "contractTxHash");
			return (Criteria) this;
		}

		public Criteria andContractTxHashLessThanOrEqualTo(String value) {
			addCriterion("contract_tx_hash <=", value, "contractTxHash");
			return (Criteria) this;
		}

		public Criteria andContractTxHashLike(String value) {
			addCriterion("contract_tx_hash like", value, "contractTxHash");
			return (Criteria) this;
		}

		public Criteria andContractTxHashNotLike(String value) {
			addCriterion("contract_tx_hash not like", value, "contractTxHash");
			return (Criteria) this;
		}

		public Criteria andContractTxHashIn(List<String> values) {
			addCriterion("contract_tx_hash in", values, "contractTxHash");
			return (Criteria) this;
		}

		public Criteria andContractTxHashNotIn(List<String> values) {
			addCriterion("contract_tx_hash not in", values, "contractTxHash");
			return (Criteria) this;
		}

		public Criteria andContractTxHashBetween(String value1, String value2) {
			addCriterion("contract_tx_hash between", value1, value2, "contractTxHash");
			return (Criteria) this;
		}

		public Criteria andContractTxHashNotBetween(String value1, String value2) {
			addCriterion("contract_tx_hash not between", value1, value2, "contractTxHash");
			return (Criteria) this;
		}

		public Criteria andContractTypeIsNull() {
			addCriterion("contract_type is null");
			return (Criteria) this;
		}

		public Criteria andContractTypeIsNotNull() {
			addCriterion("contract_type is not null");
			return (Criteria) this;
		}

		public Criteria andContractTypeEqualTo(String value) {
			addCriterion("contract_type =", value, "contractType");
			return (Criteria) this;
		}

		public Criteria andContractTypeNotEqualTo(String value) {
			addCriterion("contract_type <>", value, "contractType");
			return (Criteria) this;
		}

		public Criteria andContractTypeGreaterThan(String value) {
			addCriterion("contract_type >", value, "contractType");
			return (Criteria) this;
		}

		public Criteria andContractTypeGreaterThanOrEqualTo(String value) {
			addCriterion("contract_type >=", value, "contractType");
			return (Criteria) this;
		}

		public Criteria andContractTypeLessThan(String value) {
			addCriterion("contract_type <", value, "contractType");
			return (Criteria) this;
		}

		public Criteria andContractTypeLessThanOrEqualTo(String value) {
			addCriterion("contract_type <=", value, "contractType");
			return (Criteria) this;
		}

		public Criteria andContractTypeLike(String value) {
			addCriterion("contract_type like", value, "contractType");
			return (Criteria) this;
		}

		public Criteria andContractTypeNotLike(String value) {
			addCriterion("contract_type not like", value, "contractType");
			return (Criteria) this;
		}

		public Criteria andContractTypeIn(List<String> values) {
			addCriterion("contract_type in", values, "contractType");
			return (Criteria) this;
		}

		public Criteria andContractTypeNotIn(List<String> values) {
			addCriterion("contract_type not in", values, "contractType");
			return (Criteria) this;
		}

		public Criteria andContractTypeBetween(String value1, String value2) {
			addCriterion("contract_type between", value1, value2, "contractType");
			return (Criteria) this;
		}

		public Criteria andContractTypeNotBetween(String value1, String value2) {
			addCriterion("contract_type not between", value1, value2, "contractType");
			return (Criteria) this;
		}

		public Criteria andContractNameIsNull() {
			addCriterion("contract_name is null");
			return (Criteria) this;
		}

		public Criteria andContractNameIsNotNull() {
			addCriterion("contract_name is not null");
			return (Criteria) this;
		}

		public Criteria andContractNameEqualTo(String value) {
			addCriterion("contract_name =", value, "contractName");
			return (Criteria) this;
		}

		public Criteria andContractNameNotEqualTo(String value) {
			addCriterion("contract_name <>", value, "contractName");
			return (Criteria) this;
		}

		public Criteria andContractNameGreaterThan(String value) {
			addCriterion("contract_name >", value, "contractName");
			return (Criteria) this;
		}

		public Criteria andContractNameGreaterThanOrEqualTo(String value) {
			addCriterion("contract_name >=", value, "contractName");
			return (Criteria) this;
		}

		public Criteria andContractNameLessThan(String value) {
			addCriterion("contract_name <", value, "contractName");
			return (Criteria) this;
		}

		public Criteria andContractNameLessThanOrEqualTo(String value) {
			addCriterion("contract_name <=", value, "contractName");
			return (Criteria) this;
		}

		public Criteria andContractNameLike(String value) {
			addCriterion("contract_name like", value, "contractName");
			return (Criteria) this;
		}

		public Criteria andContractNameNotLike(String value) {
			addCriterion("contract_name not like", value, "contractName");
			return (Criteria) this;
		}

		public Criteria andContractNameIn(List<String> values) {
			addCriterion("contract_name in", values, "contractName");
			return (Criteria) this;
		}

		public Criteria andContractNameNotIn(List<String> values) {
			addCriterion("contract_name not in", values, "contractName");
			return (Criteria) this;
		}

		public Criteria andContractNameBetween(String value1, String value2) {
			addCriterion("contract_name between", value1, value2, "contractName");
			return (Criteria) this;
		}

		public Criteria andContractNameNotBetween(String value1, String value2) {
			addCriterion("contract_name not between", value1, value2, "contractName");
			return (Criteria) this;
		}

		public Criteria andContractStatusIsNull() {
			addCriterion("contract_status is null");
			return (Criteria) this;
		}

		public Criteria andContractStatusIsNotNull() {
			addCriterion("contract_status is not null");
			return (Criteria) this;
		}

		public Criteria andContractStatusEqualTo(String value) {
			addCriterion("contract_status =", value, "contractStatus");
			return (Criteria) this;
		}

		public Criteria andContractStatusNotEqualTo(String value) {
			addCriterion("contract_status <>", value, "contractStatus");
			return (Criteria) this;
		}

		public Criteria andContractStatusGreaterThan(String value) {
			addCriterion("contract_status >", value, "contractStatus");
			return (Criteria) this;
		}

		public Criteria andContractStatusGreaterThanOrEqualTo(String value) {
			addCriterion("contract_status >=", value, "contractStatus");
			return (Criteria) this;
		}

		public Criteria andContractStatusLessThan(String value) {
			addCriterion("contract_status <", value, "contractStatus");
			return (Criteria) this;
		}

		public Criteria andContractStatusLessThanOrEqualTo(String value) {
			addCriterion("contract_status <=", value, "contractStatus");
			return (Criteria) this;
		}

		public Criteria andContractStatusLike(String value) {
			addCriterion("contract_status like", value, "contractStatus");
			return (Criteria) this;
		}

		public Criteria andContractStatusNotLike(String value) {
			addCriterion("contract_status not like", value, "contractStatus");
			return (Criteria) this;
		}

		public Criteria andContractStatusIn(List<String> values) {
			addCriterion("contract_status in", values, "contractStatus");
			return (Criteria) this;
		}

		public Criteria andContractStatusNotIn(List<String> values) {
			addCriterion("contract_status not in", values, "contractStatus");
			return (Criteria) this;
		}

		public Criteria andContractStatusBetween(String value1, String value2) {
			addCriterion("contract_status between", value1, value2, "contractStatus");
			return (Criteria) this;
		}

		public Criteria andContractStatusNotBetween(String value1, String value2) {
			addCriterion("contract_status not between", value1, value2, "contractStatus");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeIsNull() {
			addCriterion("created_time is null");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeIsNotNull() {
			addCriterion("created_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeEqualTo(Date value) {
			addCriterion("created_time =", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeNotEqualTo(Date value) {
			addCriterion("created_time <>", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeGreaterThan(Date value) {
			addCriterion("created_time >", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("created_time >=", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeLessThan(Date value) {
			addCriterion("created_time <", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
			addCriterion("created_time <=", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeIn(List<Date> values) {
			addCriterion("created_time in", values, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeNotIn(List<Date> values) {
			addCriterion("created_time not in", values, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeBetween(Date value1, Date value2) {
			addCriterion("created_time between", value1, value2, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
			addCriterion("created_time not between", value1, value2, "createdTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeIsNull() {
			addCriterion("updated_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeIsNotNull() {
			addCriterion("updated_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeEqualTo(Date value) {
			addCriterion("updated_time =", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeNotEqualTo(Date value) {
			addCriterion("updated_time <>", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeGreaterThan(Date value) {
			addCriterion("updated_time >", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("updated_time >=", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeLessThan(Date value) {
			addCriterion("updated_time <", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeLessThanOrEqualTo(Date value) {
			addCriterion("updated_time <=", value, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeIn(List<Date> values) {
			addCriterion("updated_time in", values, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeNotIn(List<Date> values) {
			addCriterion("updated_time not in", values, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeBetween(Date value1, Date value2) {
			addCriterion("updated_time between", value1, value2, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andUpdatedTimeNotBetween(Date value1, Date value2) {
			addCriterion("updated_time not between", value1, value2, "updatedTime");
			return (Criteria) this;
		}

		public Criteria andReserved1IsNull() {
			addCriterion("reserved1 is null");
			return (Criteria) this;
		}

		public Criteria andReserved1IsNotNull() {
			addCriterion("reserved1 is not null");
			return (Criteria) this;
		}

		public Criteria andReserved1EqualTo(String value) {
			addCriterion("reserved1 =", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1NotEqualTo(String value) {
			addCriterion("reserved1 <>", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1GreaterThan(String value) {
			addCriterion("reserved1 >", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1GreaterThanOrEqualTo(String value) {
			addCriterion("reserved1 >=", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1LessThan(String value) {
			addCriterion("reserved1 <", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1LessThanOrEqualTo(String value) {
			addCriterion("reserved1 <=", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1Like(String value) {
			addCriterion("reserved1 like", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1NotLike(String value) {
			addCriterion("reserved1 not like", value, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1In(List<String> values) {
			addCriterion("reserved1 in", values, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1NotIn(List<String> values) {
			addCriterion("reserved1 not in", values, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1Between(String value1, String value2) {
			addCriterion("reserved1 between", value1, value2, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved1NotBetween(String value1, String value2) {
			addCriterion("reserved1 not between", value1, value2, "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved2IsNull() {
			addCriterion("reserved2 is null");
			return (Criteria) this;
		}

		public Criteria andReserved2IsNotNull() {
			addCriterion("reserved2 is not null");
			return (Criteria) this;
		}

		public Criteria andReserved2EqualTo(String value) {
			addCriterion("reserved2 =", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2NotEqualTo(String value) {
			addCriterion("reserved2 <>", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2GreaterThan(String value) {
			addCriterion("reserved2 >", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2GreaterThanOrEqualTo(String value) {
			addCriterion("reserved2 >=", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2LessThan(String value) {
			addCriterion("reserved2 <", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2LessThanOrEqualTo(String value) {
			addCriterion("reserved2 <=", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2Like(String value) {
			addCriterion("reserved2 like", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2NotLike(String value) {
			addCriterion("reserved2 not like", value, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2In(List<String> values) {
			addCriterion("reserved2 in", values, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2NotIn(List<String> values) {
			addCriterion("reserved2 not in", values, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2Between(String value1, String value2) {
			addCriterion("reserved2 between", value1, value2, "reserved2");
			return (Criteria) this;
		}

		public Criteria andReserved2NotBetween(String value1, String value2) {
			addCriterion("reserved2 not between", value1, value2, "reserved2");
			return (Criteria) this;
		}

		public Criteria andContractIdLikeInsensitive(String value) {
			addCriterion("upper(contract_id) like", value.toUpperCase(), "contractId");
			return (Criteria) this;
		}

		public Criteria andContractAddressLikeInsensitive(String value) {
			addCriterion("upper(contract_address) like", value.toUpperCase(), "contractAddress");
			return (Criteria) this;
		}

		public Criteria andContractTxHashLikeInsensitive(String value) {
			addCriterion("upper(contract_tx_hash) like", value.toUpperCase(), "contractTxHash");
			return (Criteria) this;
		}

		public Criteria andContractTypeLikeInsensitive(String value) {
			addCriterion("upper(contract_type) like", value.toUpperCase(), "contractType");
			return (Criteria) this;
		}

		public Criteria andContractNameLikeInsensitive(String value) {
			addCriterion("upper(contract_name) like", value.toUpperCase(), "contractName");
			return (Criteria) this;
		}

		public Criteria andContractStatusLikeInsensitive(String value) {
			addCriterion("upper(contract_status) like", value.toUpperCase(), "contractStatus");
			return (Criteria) this;
		}

		public Criteria andReserved1LikeInsensitive(String value) {
			addCriterion("upper(reserved1) like", value.toUpperCase(), "reserved1");
			return (Criteria) this;
		}

		public Criteria andReserved2LikeInsensitive(String value) {
			addCriterion("upper(reserved2) like", value.toUpperCase(), "reserved2");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table csc_wlt_contract
	 *
	 * @mbggenerated do_not_delete_during_merge Fri Jun 08 18:04:10 CST 2018
	 */
	public static class Criteria extends GeneratedCriteria {

		public Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Data
	@NoArgsConstructor
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		public Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		public Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		public Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		public Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}