package org.csc.wlt.entity;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
public class CscWltParameterKey {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column csc_wlt_parameter.param_id
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private Integer paramId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column csc_wlt_parameter.param_id
	 *
	 * @return the value of csc_wlt_parameter.param_id
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public Integer getParamId() {
		return paramId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column csc_wlt_parameter.param_id
	 *
	 * @param paramId the value for csc_wlt_parameter.param_id
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setParamId(Integer paramId) {
		this.paramId = paramId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_parameter
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		CscWltParameterKey other = (CscWltParameterKey) that;
		return (this.getParamId() == null ? other.getParamId() == null : this.getParamId().equals(other.getParamId()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_parameter
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getParamId() == null) ? 0 : getParamId().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_parameter
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", paramId=").append(paramId);
		sb.append("]");
		return sb.toString();
	}
}