package org.csc.wlt.entity;

import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;

@Tab(name = "csc_wlt_tx")
@AllArgsConstructor
@NoArgsConstructor
public class CscWltTx extends CscWltTxKey {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cwv_wlt_tx.tx_hash
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private String txHash;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cwv_wlt_tx.input_address
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private String inputAddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cwv_wlt_tx.output_address
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private String outputAddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cwv_wlt_tx.amount
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private Long amount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cwv_wlt_tx.tx_status
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private String txStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cwv_wlt_tx.tx_type
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private String txType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cwv_wlt_tx.created_time
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private Date createdTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cwv_wlt_tx.updated_time
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private Date updatedTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cwv_wlt_tx.reserved1
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private String reserved1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cwv_wlt_tx.reserved2
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	private String reserved2;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cwv_wlt_tx.tx_hash
	 *
	 * @return the value of cwv_wlt_tx.tx_hash
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getTxHash() {
		return txHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cwv_wlt_tx.tx_hash
	 *
	 * @param txHash the value for cwv_wlt_tx.tx_hash
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setTxHash(String txHash) {
		this.txHash = txHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cwv_wlt_tx.input_address
	 *
	 * @return the value of cwv_wlt_tx.input_address
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getInputAddress() {
		return inputAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cwv_wlt_tx.input_address
	 *
	 * @param inputAddress the value for cwv_wlt_tx.input_address
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setInputAddress(String inputAddress) {
		this.inputAddress = inputAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cwv_wlt_tx.output_address
	 *
	 * @return the value of cwv_wlt_tx.output_address
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getOutputAddress() {
		return outputAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cwv_wlt_tx.output_address
	 *
	 * @param outputAddress the value for cwv_wlt_tx.output_address
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setOutputAddress(String outputAddress) {
		this.outputAddress = outputAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cwv_wlt_tx.amount
	 *
	 * @return the value of cwv_wlt_tx.amount
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public Long getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cwv_wlt_tx.amount
	 *
	 * @param amount the value for cwv_wlt_tx.amount
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setAmount(Long amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cwv_wlt_tx.tx_status
	 *
	 * @return the value of cwv_wlt_tx.tx_status
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getTxStatus() {
		return txStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cwv_wlt_tx.tx_status
	 *
	 * @param txStatus the value for cwv_wlt_tx.tx_status
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setTxStatus(String txStatus) {
		this.txStatus = txStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cwv_wlt_tx.tx_type
	 *
	 * @return the value of cwv_wlt_tx.tx_type
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getTxType() {
		return txType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cwv_wlt_tx.tx_type
	 *
	 * @param txType the value for cwv_wlt_tx.tx_type
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setTxType(String txType) {
		this.txType = txType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cwv_wlt_tx.created_time
	 *
	 * @return the value of cwv_wlt_tx.created_time
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cwv_wlt_tx.created_time
	 *
	 * @param createdTime the value for cwv_wlt_tx.created_time
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cwv_wlt_tx.updated_time
	 *
	 * @return the value of cwv_wlt_tx.updated_time
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public Date getUpdatedTime() {
		return updatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cwv_wlt_tx.updated_time
	 *
	 * @param updatedTime the value for cwv_wlt_tx.updated_time
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cwv_wlt_tx.reserved1
	 *
	 * @return the value of cwv_wlt_tx.reserved1
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getReserved1() {
		return reserved1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cwv_wlt_tx.reserved1
	 *
	 * @param reserved1 the value for cwv_wlt_tx.reserved1
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setReserved1(String reserved1) {
		this.reserved1 = reserved1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cwv_wlt_tx.reserved2
	 *
	 * @return the value of cwv_wlt_tx.reserved2
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String getReserved2() {
		return reserved2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cwv_wlt_tx.reserved2
	 *
	 * @param reserved2 the value for cwv_wlt_tx.reserved2
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public void setReserved2(String reserved2) {
		this.reserved2 = reserved2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		CscWltTx other = (CscWltTx) that;
		return (this.getTxId() == null ? other.getTxId() == null : this.getTxId().equals(other.getTxId()))
				&& (this.getTxHash() == null ? other.getTxHash() == null : this.getTxHash().equals(other.getTxHash()))
				&& (this.getInputAddress() == null ? other.getInputAddress() == null
						: this.getInputAddress().equals(other.getInputAddress()))
				&& (this.getOutputAddress() == null ? other.getOutputAddress() == null
						: this.getOutputAddress().equals(other.getOutputAddress()))
				&& (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
				&& (this.getTxStatus() == null ? other.getTxStatus() == null
						: this.getTxStatus().equals(other.getTxStatus()))
				&& (this.getTxType() == null ? other.getTxType() == null : this.getTxType().equals(other.getTxType()))
				&& (this.getCreatedTime() == null ? other.getCreatedTime() == null
						: this.getCreatedTime().equals(other.getCreatedTime()))
				&& (this.getUpdatedTime() == null ? other.getUpdatedTime() == null
						: this.getUpdatedTime().equals(other.getUpdatedTime()))
				&& (this.getReserved1() == null ? other.getReserved1() == null
						: this.getReserved1().equals(other.getReserved1()))
				&& (this.getReserved2() == null ? other.getReserved2() == null
						: this.getReserved2().equals(other.getReserved2()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getTxId() == null) ? 0 : getTxId().hashCode());
		result = prime * result + ((getTxHash() == null) ? 0 : getTxHash().hashCode());
		result = prime * result + ((getInputAddress() == null) ? 0 : getInputAddress().hashCode());
		result = prime * result + ((getOutputAddress() == null) ? 0 : getOutputAddress().hashCode());
		result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
		result = prime * result + ((getTxStatus() == null) ? 0 : getTxStatus().hashCode());
		result = prime * result + ((getTxType() == null) ? 0 : getTxType().hashCode());
		result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
		result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
		result = prime * result + ((getReserved1() == null) ? 0 : getReserved1().hashCode());
		result = prime * result + ((getReserved2() == null) ? 0 : getReserved2().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", txHash=").append(txHash);
		sb.append(", inputAddress=").append(inputAddress);
		sb.append(", outputAddress=").append(outputAddress);
		sb.append(", amount=").append(amount);
		sb.append(", txStatus=").append(txStatus);
		sb.append(", txType=").append(txType);
		sb.append(", createdTime=").append(createdTime);
		sb.append(", updatedTime=").append(updatedTime);
		sb.append(", reserved1=").append(reserved1);
		sb.append(", reserved2=").append(reserved2);
		sb.append("]");
		return sb.toString();
	}
}