package org.csc.wlt.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import org.csc.wlt.entity.CscWltTx;
import org.csc.wlt.entity.CscWltTxExample.Criteria;
import org.csc.wlt.entity.CscWltTxExample.Criterion;
import org.csc.wlt.entity.CscWltTxExample;

public class CscWltTxSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String countByExample(CscWltTxExample example) {
		BEGIN();
		SELECT("count(*)");
		FROM("cwv_wlt_tx");
		applyWhere(example, false);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String deleteByExample(CscWltTxExample example) {
		BEGIN();
		DELETE_FROM("cwv_wlt_tx");
		applyWhere(example, false);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String insertSelective(CscWltTx record) {
		BEGIN();
		INSERT_INTO("cwv_wlt_tx");

		if (record.getTxId() != null) {
			VALUES("tx_id", "#{txId,jdbcType=VARCHAR}");
		}

		if (record.getTxHash() != null) {
			VALUES("tx_hash", "#{txHash,jdbcType=VARCHAR}");
		}

		if (record.getInputAddress() != null) {
			VALUES("input_address", "#{inputAddress,jdbcType=VARCHAR}");
		}

		if (record.getOutputAddress() != null) {
			VALUES("output_address", "#{outputAddress,jdbcType=VARCHAR}");
		}

		if (record.getAmount() != null) {
			VALUES("amount", "#{amount,jdbcType=BIGINT}");
		}

		if (record.getTxStatus() != null) {
			VALUES("tx_status", "#{txStatus,jdbcType=VARCHAR}");
		}

		if (record.getTxType() != null) {
			VALUES("tx_type", "#{txType,jdbcType=VARCHAR}");
		}

		if (record.getCreatedTime() != null) {
			VALUES("created_time", "#{createdTime,jdbcType=TIMESTAMP}");
		}

		if (record.getUpdatedTime() != null) {
			VALUES("updated_time", "#{updatedTime,jdbcType=TIMESTAMP}");
		}

		if (record.getReserved1() != null) {
			VALUES("reserved1", "#{reserved1,jdbcType=VARCHAR}");
		}

		if (record.getReserved2() != null) {
			VALUES("reserved2", "#{reserved2,jdbcType=VARCHAR}");
		}

		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String selectByExample(CscWltTxExample example) {
		BEGIN();
		if (example != null && example.isDistinct()) {
			SELECT_DISTINCT("tx_id");
		} else {
			SELECT("tx_id");
		}
		SELECT("tx_hash");
		SELECT("input_address");
		SELECT("output_address");
		SELECT("amount");
		SELECT("tx_status");
		SELECT("tx_type");
		SELECT("created_time");
		SELECT("updated_time");
		SELECT("reserved1");
		SELECT("reserved2");
		FROM("cwv_wlt_tx");
		applyWhere(example, false);

		if (example != null && example.getOrderByClause() != null) {
			ORDER_BY(example.getOrderByClause());
		}

		if (example != null && example.getSelectCols() != null && example.getSelectCols().trim().length() > 0) {
			BEGIN();
			if (example != null && example.isDistinct()) {
				SELECT_DISTINCT(example.getSelectCols());
			} else {
				SELECT(example.getSelectCols());
			}
			FROM("cwv_wlt_tx");
			applyWhere(example, false);
		}
		if (example != null) {
			if (example.getLimit() != Integer.MAX_VALUE && example.getOffset() >= 0) {
				String retstr = SQL().concat(" limit " + example.getOffset() + "," + example.getLimit());
				if (example.isForUpdate()) {
					return retstr + "  FOR UPDATE ";
				} else {
					return retstr;
				}
			} else if (example.isForUpdate()) {
				return SQL() + "  FOR UPDATE ";
			}
		}
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		CscWltTx record = (CscWltTx) parameter.get("record");
		CscWltTxExample example = (CscWltTxExample) parameter.get("example");

		BEGIN();
		UPDATE("cwv_wlt_tx");

		if (record.getTxId() != null) {
			SET("tx_id = #{record.txId,jdbcType=VARCHAR}");
		}

		if (record.getTxHash() != null) {
			SET("tx_hash = #{record.txHash,jdbcType=VARCHAR}");
		}

		if (record.getInputAddress() != null) {
			SET("input_address = #{record.inputAddress,jdbcType=VARCHAR}");
		}

		if (record.getOutputAddress() != null) {
			SET("output_address = #{record.outputAddress,jdbcType=VARCHAR}");
		}

		if (record.getAmount() != null) {
			SET("amount = #{record.amount,jdbcType=BIGINT}");
		}

		if (record.getTxStatus() != null) {
			SET("tx_status = #{record.txStatus,jdbcType=VARCHAR}");
		}

		if (record.getTxType() != null) {
			SET("tx_type = #{record.txType,jdbcType=VARCHAR}");
		}

		if (record.getCreatedTime() != null) {
			SET("created_time = #{record.createdTime,jdbcType=TIMESTAMP}");
		}

		if (record.getUpdatedTime() != null) {
			SET("updated_time = #{record.updatedTime,jdbcType=TIMESTAMP}");
		}

		if (record.getReserved1() != null) {
			SET("reserved1 = #{record.reserved1,jdbcType=VARCHAR}");
		}

		if (record.getReserved2() != null) {
			SET("reserved2 = #{record.reserved2,jdbcType=VARCHAR}");
		}

		applyWhere(example, true);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String updateByExample(Map<String, Object> parameter) {
		BEGIN();
		UPDATE("cwv_wlt_tx");

		SET("tx_id = #{record.txId,jdbcType=VARCHAR}");
		SET("tx_hash = #{record.txHash,jdbcType=VARCHAR}");
		SET("input_address = #{record.inputAddress,jdbcType=VARCHAR}");
		SET("output_address = #{record.outputAddress,jdbcType=VARCHAR}");
		SET("amount = #{record.amount,jdbcType=BIGINT}");
		SET("tx_status = #{record.txStatus,jdbcType=VARCHAR}");
		SET("tx_type = #{record.txType,jdbcType=VARCHAR}");
		SET("created_time = #{record.createdTime,jdbcType=TIMESTAMP}");
		SET("updated_time = #{record.updatedTime,jdbcType=TIMESTAMP}");
		SET("reserved1 = #{record.reserved1,jdbcType=VARCHAR}");
		SET("reserved2 = #{record.reserved2,jdbcType=VARCHAR}");

		CscWltTxExample example = (CscWltTxExample) parameter.get("example");
		applyWhere(example, true);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	public String updateByPrimaryKeySelective(CscWltTx record) {
		BEGIN();
		UPDATE("cwv_wlt_tx");

		if (record.getTxHash() != null) {
			SET("tx_hash = #{txHash,jdbcType=VARCHAR}");
		}

		if (record.getInputAddress() != null) {
			SET("input_address = #{inputAddress,jdbcType=VARCHAR}");
		}

		if (record.getOutputAddress() != null) {
			SET("output_address = #{outputAddress,jdbcType=VARCHAR}");
		}

		if (record.getAmount() != null) {
			SET("amount = #{amount,jdbcType=BIGINT}");
		}

		if (record.getTxStatus() != null) {
			SET("tx_status = #{txStatus,jdbcType=VARCHAR}");
		}

		if (record.getTxType() != null) {
			SET("tx_type = #{txType,jdbcType=VARCHAR}");
		}

		if (record.getCreatedTime() != null) {
			SET("created_time = #{createdTime,jdbcType=TIMESTAMP}");
		}

		if (record.getUpdatedTime() != null) {
			SET("updated_time = #{updatedTime,jdbcType=TIMESTAMP}");
		}

		if (record.getReserved1() != null) {
			SET("reserved1 = #{reserved1,jdbcType=VARCHAR}");
		}

		if (record.getReserved2() != null) {
			SET("reserved2 = #{reserved2,jdbcType=VARCHAR}");
		}

		WHERE("tx_id = #{txId,jdbcType=VARCHAR}");

		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cwv_wlt_tx
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	protected void applyWhere(CscWltTxExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}

		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}

		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}

				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}

					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}

		if (sb.length() > 0) {
			WHERE(sb.toString());
		}
	}
}