package org.csc.wlt.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.csc.wlt.entity.CscWltContract;
import org.csc.wlt.entity.CscWltContractExample;
import org.csc.wlt.entity.CscWltContractKey;

import onight.tfw.ojpa.ordb.StaticTableDaoSupport;

public interface CscWltContractMapper
		extends StaticTableDaoSupport<CscWltContract, CscWltContractExample, CscWltContractKey> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@SelectProvider(type = CscWltContractSqlProvider.class, method = "countByExample")
	int countByExample(CscWltContractExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@DeleteProvider(type = CscWltContractSqlProvider.class, method = "deleteByExample")
	int deleteByExample(CscWltContractExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Delete({ "delete from csc_wlt_contract", "where contract_id = #{contractId,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(CscWltContractKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Insert({ "insert into csc_wlt_contract (contract_id, contract_address, ", "contract_tx_hash, contract_type, ",
			"contract_name, contract_status, ", "created_time, updated_time, ", "reserved1, reserved2)",
			"values (#{contractId,jdbcType=VARCHAR}, #{contractAddress,jdbcType=VARCHAR}, ",
			"#{contractTxHash,jdbcType=VARCHAR}, #{contractType,jdbcType=VARCHAR}, ",
			"#{contractName,jdbcType=VARCHAR}, #{contractStatus,jdbcType=VARCHAR}, ",
			"#{createdTime,jdbcType=TIMESTAMP}, #{updatedTime,jdbcType=TIMESTAMP}, ",
			"#{reserved1,jdbcType=VARCHAR}, #{reserved2,jdbcType=VARCHAR})" })
	int insert(CscWltContract record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@InsertProvider(type = CscWltContractSqlProvider.class, method = "insertSelective")
	int insertSelective(CscWltContract record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@SelectProvider(type = CscWltContractSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "contract_id", property = "contractId", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "contract_address", property = "contractAddress", jdbcType = JdbcType.VARCHAR),
			@Result(column = "contract_tx_hash", property = "contractTxHash", jdbcType = JdbcType.VARCHAR),
			@Result(column = "contract_type", property = "contractType", jdbcType = JdbcType.VARCHAR),
			@Result(column = "contract_name", property = "contractName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "contract_status", property = "contractStatus", jdbcType = JdbcType.VARCHAR),
			@Result(column = "created_time", property = "createdTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "updated_time", property = "updatedTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "reserved1", property = "reserved1", jdbcType = JdbcType.VARCHAR),
			@Result(column = "reserved2", property = "reserved2", jdbcType = JdbcType.VARCHAR) })
	List<CscWltContract> selectByExample(CscWltContractExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Select({ "select", "contract_id, contract_address, contract_tx_hash, contract_type, contract_name, ",
			"contract_status, created_time, updated_time, reserved1, reserved2", "from csc_wlt_contract",
			"where contract_id = #{contractId,jdbcType=VARCHAR}" })
	@Results({ @Result(column = "contract_id", property = "contractId", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "contract_address", property = "contractAddress", jdbcType = JdbcType.VARCHAR),
			@Result(column = "contract_tx_hash", property = "contractTxHash", jdbcType = JdbcType.VARCHAR),
			@Result(column = "contract_type", property = "contractType", jdbcType = JdbcType.VARCHAR),
			@Result(column = "contract_name", property = "contractName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "contract_status", property = "contractStatus", jdbcType = JdbcType.VARCHAR),
			@Result(column = "created_time", property = "createdTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "updated_time", property = "updatedTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "reserved1", property = "reserved1", jdbcType = JdbcType.VARCHAR),
			@Result(column = "reserved2", property = "reserved2", jdbcType = JdbcType.VARCHAR) })
	CscWltContract selectByPrimaryKey(CscWltContractKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@UpdateProvider(type = CscWltContractSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") CscWltContract record,
			@Param("example") CscWltContractExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@UpdateProvider(type = CscWltContractSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") CscWltContract record, @Param("example") CscWltContractExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@UpdateProvider(type = CscWltContractSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(CscWltContract record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Update({ "update csc_wlt_contract", "set contract_address = #{contractAddress,jdbcType=VARCHAR},",
			"contract_tx_hash = #{contractTxHash,jdbcType=VARCHAR},",
			"contract_type = #{contractType,jdbcType=VARCHAR},", "contract_name = #{contractName,jdbcType=VARCHAR},",
			"contract_status = #{contractStatus,jdbcType=VARCHAR},",
			"created_time = #{createdTime,jdbcType=TIMESTAMP},", "updated_time = #{updatedTime,jdbcType=TIMESTAMP},",
			"reserved1 = #{reserved1,jdbcType=VARCHAR},", "reserved2 = #{reserved2,jdbcType=VARCHAR}",
			"where contract_id = #{contractId,jdbcType=VARCHAR}" })
	int updateByPrimaryKey(CscWltContract record);
}