package org.csc.wlt.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.csc.wlt.entity.CscWltContractRecord;
import org.csc.wlt.entity.CscWltContractRecordExample;
import org.csc.wlt.entity.CscWltContractRecordKey;

import onight.tfw.ojpa.ordb.StaticTableDaoSupport;

public interface CscWltContractRecordMapper
		extends StaticTableDaoSupport<CscWltContractRecord, CscWltContractRecordExample, CscWltContractRecordKey> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@SelectProvider(type = CscWltContractRecordSqlProvider.class, method = "countByExample")
	int countByExample(CscWltContractRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@DeleteProvider(type = CscWltContractRecordSqlProvider.class, method = "deleteByExample")
	int deleteByExample(CscWltContractRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Delete({ "delete from csc_wlt_contract_record", "where recoed_id = #{recoedId,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(CscWltContractRecordKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Insert({ "insert into csc_wlt_contract_record (recoed_id, contract_id, ", "record_type, address, ",
			"tx_hash, created_time, ", "updated_time, reserved1, ", "reserved2)",
			"values (#{recoedId,jdbcType=VARCHAR}, #{contractId,jdbcType=VARCHAR}, ",
			"#{recordType,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
			"#{txHash,jdbcType=VARCHAR}, #{createdTime,jdbcType=TIMESTAMP}, ",
			"#{updatedTime,jdbcType=TIMESTAMP}, #{reserved1,jdbcType=VARCHAR}, ", "#{reserved2,jdbcType=VARCHAR})" })
	int insert(CscWltContractRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@InsertProvider(type = CscWltContractRecordSqlProvider.class, method = "insertSelective")
	int insertSelective(CscWltContractRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@SelectProvider(type = CscWltContractRecordSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "recoed_id", property = "recoedId", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "contract_id", property = "contractId", jdbcType = JdbcType.VARCHAR),
			@Result(column = "record_type", property = "recordType", jdbcType = JdbcType.VARCHAR),
			@Result(column = "address", property = "address", jdbcType = JdbcType.VARCHAR),
			@Result(column = "tx_hash", property = "txHash", jdbcType = JdbcType.VARCHAR),
			@Result(column = "created_time", property = "createdTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "updated_time", property = "updatedTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "reserved1", property = "reserved1", jdbcType = JdbcType.VARCHAR),
			@Result(column = "reserved2", property = "reserved2", jdbcType = JdbcType.VARCHAR) })
	List<CscWltContractRecord> selectByExample(CscWltContractRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Select({ "select", "recoed_id, contract_id, record_type, address, tx_hash, created_time, updated_time, ",
			"reserved1, reserved2", "from csc_wlt_contract_record", "where recoed_id = #{recoedId,jdbcType=VARCHAR}" })
	@Results({ @Result(column = "recoed_id", property = "recoedId", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "contract_id", property = "contractId", jdbcType = JdbcType.VARCHAR),
			@Result(column = "record_type", property = "recordType", jdbcType = JdbcType.VARCHAR),
			@Result(column = "address", property = "address", jdbcType = JdbcType.VARCHAR),
			@Result(column = "tx_hash", property = "txHash", jdbcType = JdbcType.VARCHAR),
			@Result(column = "created_time", property = "createdTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "updated_time", property = "updatedTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "reserved1", property = "reserved1", jdbcType = JdbcType.VARCHAR),
			@Result(column = "reserved2", property = "reserved2", jdbcType = JdbcType.VARCHAR) })
	CscWltContractRecord selectByPrimaryKey(CscWltContractRecordKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@UpdateProvider(type = CscWltContractRecordSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") CscWltContractRecord record,
			@Param("example") CscWltContractRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@UpdateProvider(type = CscWltContractRecordSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") CscWltContractRecord record,
			@Param("example") CscWltContractRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@UpdateProvider(type = CscWltContractRecordSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(CscWltContractRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table csc_wlt_contract_record
	 *
	 * @mbggenerated Fri Jun 08 18:04:10 CST 2018
	 */
	@Update({ "update csc_wlt_contract_record", "set contract_id = #{contractId,jdbcType=VARCHAR},",
			"record_type = #{recordType,jdbcType=VARCHAR},", "address = #{address,jdbcType=VARCHAR},",
			"tx_hash = #{txHash,jdbcType=VARCHAR},", "created_time = #{createdTime,jdbcType=TIMESTAMP},",
			"updated_time = #{updatedTime,jdbcType=TIMESTAMP},", "reserved1 = #{reserved1,jdbcType=VARCHAR},",
			"reserved2 = #{reserved2,jdbcType=VARCHAR}", "where recoed_id = #{recoedId,jdbcType=VARCHAR}" })
	int updateByPrimaryKey(CscWltContractRecord record);
}